steps:
- name: 'node:20'
  script: |
    npm install -g npm@9.0.0 && \
    npm ci && \
    npm run build
  env:
  - 'GOOGLE_MAPS_KEY=${_GOOGLE_MAPS_KEY}'
  - 'HOST=${_HOST}'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - '-m'
    - 'rsync'
    - '-r'
    - 'dist/'
    - '${_WWW_BUCKET}/'
