steps:
- name: 'gcr.io/$PROJECT_ID/node-bc-checkout'
  entrypoint: npm
  args: ['install']
- name: 'gcr.io/$PROJECT_ID/node-bc-checkout'
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - '-m'
    - 'rsync'
    - '-r'
    - 'dist/'
    - '${_WWW_BUCKET}/'
