const stateReasons: {
  [key: string]: string[];
} = {
  Alabama: ['RESALE', 'TRIBAL GOVERNMENT'],
  Alaska: ['RESALE'],
  Alberta: [],
  'American Samoa': [],
  Arizona: ['RESALE', 'TRIBAL GOVERNMENT'],
  Arkansas: ['RESALE'],
  'British Columbia': ['RESALE', 'TRIBAL GOVERNMENT'],
  California: ['RESALE', 'TRIBAL GOVERNMENT'],
  'Canada (GST)': ['TRIBAL GOVERNMENT'],
  Colorado: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Connecticut: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Delaware: [],
  'District Of Columbia': ['RESALE'],
  Florida: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Georgia: ['LOCAL GOVERNMENT', 'RESALE'],
  Guam: [],
  Hawaii: ['RESALE'],
  Idaho: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Illinois: ['LOCAL GOVERNMENT', 'RESALE'],
  Indiana: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Iowa: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Kansas: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Kentucky: ['LOCAL GOVERNMENT', 'RESALE'],
  Louisiana: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Maine: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Manitoba: ['RESALE', 'TRIBAL GOVERNMENT'],
  Maryland: ['LOCAL GOVERNMENT', 'RESALE'],
  Massachusetts: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Michigan: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Minnesota: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Mississippi: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Missouri: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Montana: ['RESALE'],
  Nebraska: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Nevada: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  'New Brunswick': ['TRIBAL GOVERNMENT'],
  Newfoundland: ['TRIBAL GOVERNMENT'],
  'New Hampshire': [],
  'New Jersey': ['LOCAL GOVERNMENT', 'RESALE'],
  'New Mexico': ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  'New York': ['RESALE', 'TRIBAL GOVERNMENT'],
  'North Carolina': ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  'North Dakota': ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  'Northern Mariana Islands': [],
  'Northwest Territories': [],
  'Nova Scotia': ['TRIBAL GOVERNMENT'],
  Nunavut: [],
  Ohio: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Oklahoma: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Ontario: ['TRIBAL GOVERNMENT'],
  Oregon: ['RESALE'],
  Pennsylvania: ['LOCAL GOVERNMENT', 'RESALE'],
  'Prince Edward Island': ['TRIBAL GOVERNMENT'],
  'Puerto Rico': ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Quebec: ['TRIBAL GOVERNMENT'],
  'Rhode Island': ['RESALE', 'TRIBAL GOVERNMENT'],
  Saskatchewan: ['RESALE', 'TRIBAL GOVERNMENT'],
  'South Carolina': ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  'South Dakota': ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Tennessee: ['LOCAL GOVERNMENT', 'RESALE'],
  Texas: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  'U.S. Virgin Islands': [],
  Utah: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Vermont: ['LOCAL GOVERNMENT', 'RESALE'],
  Virginia: ['LOCAL GOVERNMENT', 'RESALE'],
  Washington: ['RESALE', 'TRIBAL GOVERNMENT'],
  'West Virginia': ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Wisconsin: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Wyoming: ['LOCAL GOVERNMENT', 'RESALE', 'TRIBAL GOVERNMENT'],
  Yukon: [],
};
export default stateReasons;
