const timeString = new Date().toISOString();

const checkoutSettings = {
    context: {
        flashMessages: [],
        payment: {
            token: null,
        },
        checkoutId: 'x',
        geoCountryCode: 'AU',
    },
    customization: {
        languageData: [],
    },
    storeConfig: {
        cdnPath: 'https://cdn.bigcommerce.com',
        checkoutSettings: {
            checkoutBillingSameAsShippingEnabled: true,
            hasMultiShippingEnabled: true,
            enableOrderComments: true,
            enableTermsAndConditions: false,
            guestCheckoutEnabled: true,
            isCardVaultingEnabled: true,
            isCouponCodeCollapsed: true,
            isExpressPrivacyPolicy: false,
            isPaymentRequestEnabled: false,
            isPaymentRequestCanMakePaymentEnabled: false,
            isSignInEmailEnabled: true,
            isSpamProtectionEnabled: false,
            isTrustedShippingAddressEnabled: true,
            orderTermsAndConditions: '',
            orderTermsAndConditionsLocation: 'payment',
            orderTermsAndConditionsLink: '',
            orderTermsAndConditionsType: 'textarea',
            privacyPolicyUrl: '',
            shippingQuoteFailedMessage:
                "Unfortunately one or more items in your cart can't be shipped to your location. Please choose a different delivery address.",
            isAccountCreationEnabled: true,
            realtimeShippingProviders: ['Fedex', 'UPS', 'USPS'],
            remoteCheckoutProviders: null,
            providerWithCustomCheckout: null,
            isAnalyticsEnabled: false,
            isStorefrontSpamProtectionEnabled: true,
            googleMapsApiKey: 'x',
            googleRecaptchaSitekey: 'x',
            features: {},
            requiresMarketingConsent: false,
            checkoutUserExperienceSettings: {
                walletButtonsOnTop: true,
                floatingLabelEnabled: true,
            },
        },
        currency: {
            code: 'USD',
            decimalPlaces: '2',
            decimalSeparator: '.',
            isTransactional: true,
            symbolLocation: 'left',
            symbol: '$',
            thousandsSeparator: ',',
        },
        displayDateFormat: 'do MMM yyyy',
        displaySettings: {
            hidePriceFromGuests: false,
        },
        inputDateFormat: 'dd/MM/yyyy',
        formFields: {
            billingAddressFields: [
                {
                    id: 'field_4',
                    name: 'firstName',
                    custom: false,
                    label: 'First Name',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_5',
                    name: 'lastName',
                    custom: false,
                    label: 'Last Name',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_6',
                    name: 'company',
                    custom: false,
                    label: 'Company Name',
                    required: false,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_7',
                    name: 'phone',
                    custom: false,
                    label: 'Phone Number',
                    required: false,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_8',
                    name: 'address1',
                    custom: false,
                    label: 'Address Line 1',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_9',
                    name: 'address2',
                    custom: false,
                    label: 'Address Line 2',
                    required: false,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_10',
                    name: 'city',
                    custom: false,
                    label: 'Suburb\\/City',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_11',
                    name: 'countryCode',
                    custom: false,
                    label: 'Country',
                    required: true,
                    default: null,
                    maxLength: false,
                },
                {
                    id: 'field_12',
                    name: 'stateOrProvince',
                    custom: false,
                    label: 'State\\/Province',
                    required: true,
                    default: null,
                    maxLength: '',
                },
                {
                    id: 'field_13',
                    name: 'postalCode',
                    custom: false,
                    label: 'My own Zip code',
                    required: true,
                    default: '',
                    maxLength: '',
                },
            ],
            shippingAddressFields: [
                {
                    id: 'field_14',
                    name: 'firstName',
                    custom: false,
                    label: 'First Name',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_15',
                    name: 'lastName',
                    custom: false,
                    label: 'Last Name',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_16',
                    name: 'company',
                    custom: false,
                    label: 'Company Name',
                    required: false,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_17',
                    name: 'phone',
                    custom: false,
                    label: 'Phone Number',
                    required: false,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_18',
                    name: 'address1',
                    custom: false,
                    label: 'Address Line 1',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_19',
                    name: 'address2',
                    custom: false,
                    label: 'Address Line 2',
                    required: false,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_20',
                    name: 'city',
                    custom: false,
                    label: 'Suburb\\/City',
                    required: true,
                    default: '',
                    maxLength: '',
                },
                {
                    id: 'field_21',
                    name: 'countryCode',
                    custom: false,
                    label: 'Country',
                    required: true,
                    default: null,
                    maxLength: false,
                },
                {
                    id: 'field_22',
                    name: 'stateOrProvince',
                    custom: false,
                    label: 'State\\/Province',
                    required: true,
                    default: null,
                    maxLength: '',
                },
                {
                    id: 'field_23',
                    name: 'postalCode',
                    custom: false,
                    label: 'My own Zip code',
                    required: true,
                    default: '',
                    maxLength: '',
                },
            ],
        },
        links: {
            cartLink: 'https://store.url/cart.php',
            checkoutLink: 'https://store.url/checkout',
            createAccountLink: 'https://store.url/login.php?action=create_account',
            forgotPasswordLink: 'https://store.url/login.php?action=reset_password',
            loginLink: 'https://store.url/login.php',
            orderConfirmationLink: 'https://store.url/checkout/order-confirmation',
            siteLink: 'https://store.url',
        },
        paymentSettings: {
            bigpayBaseUrl: 'https:\\/\\/payments.bigcommerce.com',
            clientSidePaymentProviders: [],
        },
        shopperConfig: {
            defaultNewsletterSignup: false,
            passwordRequirements: {
                alpha: '[A-Za-z]',
                numeric: '[0-9]',
                minlength: 7,
                error: 'Passwords must be at least 7 characters and contain both alphabetic and numeric characters.',
            },
            showNewsletterSignup: true,
        },
        storeProfile: {
            orderEmail: 'order@example.com',
            shopPath: 'https:\\/\\/store.url',
            storeCountry: 'United States',
            storeCountryCode: 'US',
            storeHash: 'x',
            storeId: 100,
            storeName: 'Store Name',
            storePhoneNumber: '',
            storeLanguage: 'en_US',
        },
        imageDirectory: 'product_images',
        isAngularDebuggingEnabled: false,
        shopperCurrency: {
            code: 'USD',
            symbolLocation: 'left',
            symbol: '$',
            decimalPlaces: '2',
            decimalSeparator: '.',
            thousandsSeparator: ',',
            exchangeRate: 1,
            isTransactional: true,
        },
    },
};

const checkoutSettingsWithUnsupportedProvider = {
    ...checkoutSettings,
    storeConfig: {
        ...checkoutSettings.storeConfig,
        checkoutSettings: {
            ...checkoutSettings.storeConfig.checkoutSettings,
            providerWithCustomCheckout: 'applepay',
        },
    },
};

const checkoutSettingsWithErrorFlashMessage = {
    ...checkoutSettings,
    context: {
        ...checkoutSettings.context,
        flashMessages: [
            {
                message: 'flash message',
                title: '',
                type: 'error',
            },
        ],
    },
};

const checkoutSettingsWithCustomErrorFlashMessage = {
    ...checkoutSettings,
    context: {
        ...checkoutSettings.context,
        flashMessages: [
            {
                message: 'flash message',
                title: 'custom error title',
                type: 'error',
            },
        ],
    },
};

const cart = {
    id: 'x',
    cart: {
        id: 'x,',
        customerId: 0,
        email: '',
        currency: {
            name: 'US Dollar',
            code: 'USD',
            symbol: '$',
            decimalPlaces: 2,
        },
        isTaxIncluded: true,
        baseAmount: 200,
        discountAmount: 0,
        cartAmount: 200,
        coupons: [],
        discounts: [
            {
                id: 'x',
                discountedAmount: 0,
            },
        ],
        lineItems: {
            physicalItems: [
                {
                    id: 'x',
                    parentId: null,
                    variantId: 71,
                    productId: 103,
                    sku: 'CLC',
                    name: '[Sample] Canvas Laundry Cart',
                    url: 'https://store.url/canvas-laundry-cart/',
                    quantity: 1,
                    brand: 'OFS',
                    isTaxable: true,
                    imageUrl: 'https://image.url',
                    discounts: [],
                    discountAmount: 0,
                    couponAmount: 0,
                    originalPrice: 249,
                    listPrice: 200,
                    salePrice: 200,
                    extendedListPrice: 200,
                    extendedSalePrice: 200,
                    comparisonPrice: 200,
                    extendedComparisonPrice: 200,
                    isShippingRequired: true,
                    giftWrapping: null,
                    addedByPromotion: false,
                    isMutable: true,
                    options: [],
                    categoryNames: ['Shop All', 'Utility'],
                },
            ],
            digitalItems: [],
            giftCertificates: [],
            customItems: [],
        },
        createdTime: timeString,
        updatedTime: timeString,
        locale: 'en',
    },
    billingAddress: {},
    consignments: [],
    orderId: null,
    shippingCostTotal: 0,
    shippingCostBeforeDiscount: 0,
    handlingCostTotal: 0,
    taxTotal: 18.18,
    giftWrappingCostTotal: 0,
    coupons: [],
    taxes: [
        {
            name: 'GST',
            amount: 18.18,
        },
    ],
    subtotal: 200,
    grandTotal: 200,
    outstandingBalance: 200,
    isStoreCreditApplied: true,
    shouldExecuteSpamCheck: false,
    giftCertificates: [],
    createdTime: timeString,
    updatedTime: timeString,
    customerMessage: '',
    channelId: 1,
    customer: {
        id: 0,
        isGuest: true,
        email: '',
        firstName: '',
        lastName: '',
        fullName: '',
        addresses: [],
        storeCredit: 0,
        shouldEncourageSignIn: false,
    },
    promotions: [],
    payments: [{}],
};

const cartWithoutPhysicalItem = {
    ...cart,
    cart: {
        ...cart.cart,
        lineItems: {
            ...cart.cart.lineItems,
            physicalItems: [],
        },
    },
};

const cartWithPromotions = {
    ...cart,
    promotions: [
        {
            banners: [
                { type: 'upsell', text: 'Get a discount if you order more' },
                { type: 'eligible', text: 'You are eligible for a discount' },
            ],
        },
    ],
};

const cartWithBillingEmail = {
    ...cart,
    billingAddress: {
        ...cart.billingAddress,
        email: 'test@example.com',
    },
};

const cartWithShippingAddress = {
    ...cartWithBillingEmail,
    consignments: [
        {
            id: 'x',
            shippingCost: 0,
            handlingCost: 0,
            couponDiscounts: [],
            discounts: [],
            lineItemIds: ['x'],
            selectedShippingOption: {
                id: 'x',
                type: 'shipping_pickupinstore',
                description: 'Pickup In Store',
                imageUrl: '',
                cost: 0,
                transitTime: '',
                additionalDescription: '',
            },
            shippingAddress: {
                firstName: 'checkout',
                lastName: 'test',
                email: '',
                company: '',
                address1: '130 Pitt St',
                address2: '',
                city: 'Sydney',
                stateOrProvince: 'New South Wales',
                stateOrProvinceCode: 'NSW',
                country: 'Australia',
                countryCode: 'AU',
                postalCode: '2000',
                phone: '',
                customFields: [],
                shouldSaveAddress: true,
            },
            address: {
                firstName: 'checkout',
                lastName: 'test',
                email: '',
                company: '',
                address1: '130 Pitt St',
                address2: '',
                city: 'Sydney',
                stateOrProvince: 'New South Wales',
                stateOrProvinceCode: 'NSW',
                country: 'Australia',
                countryCode: 'AU',
                postalCode: '2000',
                phone: '',
                customFields: [],
                shouldSaveAddress: true,
            },
            availableShippingOptions: [
                {
                    id: 'x',
                    type: 'shipping_pickupinstore',
                    description: 'Pickup In Store',
                    imageUrl: '',
                    cost: 0,
                    transitTime: '',
                    isRecommended: false,
                    additionalDescription: '',
                },
                {
                    id: 'xx',
                    type: 'shipping_flatrate',
                    description: 'Flat Rate',
                    imageUrl: '',
                    cost: 10,
                    transitTime: '',
                    isRecommended: true,
                    additionalDescription: '',
                },
            ],
        },
    ],
};

const cartWithShippingAndBilling = {
    ...cartWithShippingAddress,
    billingAddress: {
        id: 'x',
        firstName: 'checkout',
        lastName: 'test',
        email: 'test@example.com',
        company: '',
        address1: '130 Pitt St',
        address2: '',
        city: 'Sydney',
        shouldSaveAddress: true,
        stateOrProvince: 'New South Wales',
        stateOrProvinceCode: 'NSW',
        country: 'Australia',
        countryCode: 'AU',
        postalCode: '2000',
        phone: '',
        customFields: [],
    },
};

// intentionally shortened
const countries = {
    data: [
        {
            id: 1,
            code: 'AF',
            name: 'Afghanistan',
            hasPostalCodes: true,
            requiresState: false,
            subdivisions: [],
        },
        {
            id: 239,
            code: 'ZW',
            name: 'Zimbabwe',
            hasPostalCodes: false,
            requiresState: false,
            subdivisions: [],
        },
    ],
    meta: {},
};

const formFields = {
    billingAddress: [
        {
            id: 'field_4',
            name: 'firstName',
            custom: false,
            label: 'First Name',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_5',
            name: 'lastName',
            custom: false,
            label: 'Last Name',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_6',
            name: 'company',
            custom: false,
            label: 'Company Name',
            required: false,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_7',
            name: 'phone',
            custom: false,
            label: 'Phone Number',
            required: false,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_8',
            name: 'address1',
            custom: false,
            label: 'Address Line 1',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_9',
            name: 'address2',
            custom: false,
            label: 'Address Line 2',
            required: false,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_10',
            name: 'city',
            custom: false,
            label: 'Suburb\\/City',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_11',
            name: 'countryCode',
            custom: false,
            label: 'Country',
            required: true,
            default: null,
            maxLength: null,
            type: 'array',
            fieldType: 'dropdown',
            options: {
                helperLabel: 'Choose a Country',
                items: [],
            },
        },
        {
            id: 'field_12',
            name: 'stateOrProvince',
            custom: false,
            label: 'State\\/Province',
            required: true,
            default: null,
            maxLength: null,
        },
        {
            id: 'field_13',
            name: 'postalCode',
            custom: false,
            label: 'My own Zip code',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
    ],
    shippingAddress: [
        {
            id: 'field_14',
            name: 'firstName',
            custom: false,
            label: 'First Name',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_15',
            name: 'lastName',
            custom: false,
            label: 'Last Name',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_16',
            name: 'company',
            custom: false,
            label: 'Company Name',
            required: false,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_17',
            name: 'phone',
            custom: false,
            label: 'Phone Number',
            required: false,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_18',
            name: 'address1',
            custom: false,
            label: 'Address Line 1',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_19',
            name: 'address2',
            custom: false,
            label: 'Address Line 2',
            required: false,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_20',
            name: 'city',
            custom: false,
            label: 'Suburb\\/City',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_21',
            name: 'countryCode',
            custom: false,
            label: 'Country',
            required: true,
            default: null,
            maxLength: null,
            type: 'array',
            fieldType: 'dropdown',
            options: {
                helperLabel: 'Choose a Country',
                items: [],
            },
        },
        {
            id: 'field_22',
            name: 'stateOrProvince',
            custom: false,
            label: 'State\\/Province',
            required: true,
            default: null,
            maxLength: null,
        },
        {
            id: 'field_23',
            name: 'postalCode',
            custom: false,
            label: 'My own Zip code',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
    ],
    customerAccount: [
        {
            id: 'field_14',
            name: 'firstName',
            custom: false,
            label: 'First Name',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_15',
            name: 'lastName',
            custom: false,
            label: 'Last Name',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_1',
            name: 'email',
            custom: false,
            label: 'Email',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'text',
        },
        {
            id: 'field_2',
            name: 'password',
            custom: false,
            label: 'Password',
            required: true,
            default: '',
            maxLength: null,
            type: 'string',
            fieldType: 'password',
            secret: true,
            requirements: {
                alpha: '[A-Za-z]',
                description:
                    'Passwords must be at least 7 characters and contain both alphabetic and numeric characters.',
                numeric: '[0-9]',
                minlength: 7,
            },
        },
    ],
};

const payments = [
    {
        id: 'bigpaypay',
        gateway: null,
        logoUrl: '',
        method: 'zzzblackhole',
        supportedCards: ['VISA', 'AMEX', 'MC'],
        providesShippingAddress: false,
        config: {
            displayName: 'Test Payment Provider',
            cardCode: null,
            helpText: '',
            enablePaypal: null,
            merchantId: null,
            is3dsEnabled: null,
            testMode: false,
            isVisaCheckoutEnabled: null,
            requireCustomerCode: false,
            isVaultingEnabled: false,
            isVaultingCvvEnabled: null,
            hasDefaultStoredInstrument: false,
            isHostedFormEnabled: true,
            logo: null,
        },
        type: 'PAYMENT_TYPE_API',
        initializationStrategy: {
            type: 'not_applicable',
        },
        nonce: null,
        initializationData: null,
        clientToken: null,
        returnUrl: null,
    },
    {
        id: 'instore',
        gateway: null,
        logoUrl: '',
        method: 'offline',
        supportedCards: [],
        providesShippingAddress: false,
        config: {
            displayName: 'Pay in Store',
            cardCode: null,
            helpText: 'Type instructions to pay by visiting your retail store in here.',
            enablePaypal: null,
            merchantId: null,
            is3dsEnabled: null,
            testMode: false,
            isVisaCheckoutEnabled: null,
            requireCustomerCode: false,
            isVaultingEnabled: false,
            isVaultingCvvEnabled: null,
            hasDefaultStoredInstrument: false,
            isHostedFormEnabled: false,
            logo: null,
        },
        type: 'PAYMENT_TYPE_OFFLINE',
        initializationStrategy: {
            type: 'not_applicable',
        },
        nonce: null,
        initializationData: null,
        clientToken: null,
        returnUrl: null,
    },
];

export {
    cart,
    cartWithBillingEmail,
    cartWithPromotions,
    cartWithShippingAddress,
    cartWithShippingAndBilling,
    cartWithoutPhysicalItem,
    checkoutSettings,
    checkoutSettingsWithCustomErrorFlashMessage,
    checkoutSettingsWithErrorFlashMessage,
    checkoutSettingsWithUnsupportedProvider,
    countries,
    formFields,
    payments,
};
